const questions=[
["When a big project lands on your desk, you usually…",[["Break it into a logical plan","strategist"],["Turn it into a creative concept","creator"],["Explore different ways to approach it","explorer"],["Take charge and organize everyone","leader"]]],
["A free weekend sounds best when you are…",[["Learning something fascinating","explorer"],["Making art, music, or something new","creator"],["Planning your next big goal","strategist"],["Getting friends together for an experience","leader"]]],
["When making an important decision, you trust…",[["Facts and careful reasoning","strategist"],["Your imagination and intuition","creator"],["Curiosity and new possibilities","explorer"],["Confidence and your sense of responsibility","leader"]]],
["Your friends need help. Your first instinct is to…",[["Analyze the problem and find the best solution","strategist"],["Come up with an unexpected idea","creator"],["Research options and discover something useful","explorer"],["Step forward and coordinate the group","leader"]]],
["Which environment makes you feel most alive?",[["A quiet space where I can focus","strategist"],["A studio full of ideas and inspiration","creator"],["Somewhere new that I have never explored","explorer"],["A room where people are working toward a goal","leader"]]],
["When you learn something new, you prefer to…",[["Understand how and why it works","strategist"],["Experiment and put your own spin on it","creator"],["Follow questions wherever they lead","explorer"],["Practice it and help others learn too","leader"]]],
["If plans suddenly change, you…",[["Quickly make a new logical plan","strategist"],["Improvise something more interesting","creator"],["Get excited about the unexpected","explorer"],["Keep everyone calm and moving","leader"]]],
["People often come to you because you are…",[["Good at solving complicated problems","strategist"],["Full of fresh ideas","creator"],["Always curious about something","explorer"],["Someone who can take responsibility","leader"]]],
["Your ideal future feels…",[["Well-designed and intentional","strategist"],["Original and expressive","creator"],["Full of discovery and adventure","explorer"],["Impactful, ambitious, and meaningful","leader"]]],
["What would you most like people to remember about you?",[["I made smart decisions","strategist"],["I created something unique","creator"],["I never stopped learning","explorer"],["I inspired people to move forward","leader"]]]
];
const names={strategist:"THE STRATEGIST",creator:"THE CREATOR",explorer:"THE EXPLORER",leader:"THE LEADER"};
let index=0,answers=[],scores={strategist:0,creator:0,explorer:0,leader:0};
const q=document.getElementById("question"),bar=document.getElementById("bar"),counter=document.getElementById("counter"),back=document.getElementById("back");
function render(){const [text,opts]=questions[index];counter.textContent=`Question ${index+1} of ${questions.length}`;bar.style.width=((index+1)/questions.length*100)+"%";q.classList.remove("swap");void q.offsetWidth;q.classList.add("swap");q.innerHTML=`<div class="qnum">0${index+1}</div><h1>${text}</h1><p>Choose the answer that feels most like you — not the one that sounds best.</p><div class="answers">${opts.map((o,i)=>`<button class="answer" data-type="${o[1]}"><b>${String.fromCharCode(65+i)}</b>${o[0]}</button>`).join("")}</div>`;back.disabled=index===0;q.querySelectorAll(".answer").forEach(b=>b.onclick=()=>choose(b.dataset.type))}
function choose(type){answers[index]=type;if(index<questions.length-1){index++;render()}else{scores={strategist:0,creator:0,explorer:0,leader:0};answers.forEach(a=>scores[a]++);localStorage.setItem("whoamiResult",JSON.stringify({scores,answers,date:Date.now()}));location.href="result.html"}}
back.onclick=()=>{if(index>0){index--;render()}};render();